### ISSUE TITLE
Navbar Contact go to #contact form in contact page

### ISSUE THREAD

**Issue by RidaCode** [InstincDev/instincdev-portfolio#1]
Only on web view

Right now, if we click on Contact from navbar, 
it will go to the Contact page only, 
then we have to manually scroll down to the contact form

I think it would be better, 
if it takes us to the Contact page and straight to the contact form

Can use the contact ID in HTML to achieve that

Note: need to make sure that will happen if we are at any page.

Thoughts ? 👍 👎

**Comment by InstincDev** [comment]
@RidaCode 
Thank you for bringing this issue to my attention.

I planned on working portfolio issues like this today;
however, if you would like to contribute, I have no problem assigning this issue to you creating a new branch.

**Comment by RidaCode** [comment]
Sounds good I will take it

**Comment by InstincDev** [comment]
Thank you again for suggesting this navbar feature, and your contribution
